### ISSUE TITLE
Symbols are not displayed

### ISSUE THREAD

**Issue by HYDeath** [rexlManu/FairyChat#13]
![image](https://github.com/rexlManu/FairyChat/assets/65531310/9d6b6626-2e5d-4371-9031-0c5277a9099f)
I don't know what the problem is with this, using mini test name is displayed normally, but in Fairychat default configuration test name is not displayed.

**Comment by rexlManu** [comment]
Sorry for that issue. I had a bug that doesn't recognized third party plugins properly. That is fixed with version v0.3.2
