### ISSUE TITLE
Private Messaging, Ignore players

### ISSUE THREAD

**Issue by xsorencoolx** [rexlManu/FairyChat#2]
first of all if you can add /msg and /r to plugin that players private message cross server with redis it would be awesome and if you can add tab complete for players that is online like /msg [tab complete online player name] and if you can add /ignore that players ignore each other chat for private message and global message and add mysql support for ignore lists for player and add on the config sender and receiver of private message chat format

and another idea i have if you can hook your plugin with this plugin
https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/
it can be awesome to send items on chat with redis

**Comment by rexlManu** [comment]
This is completed with #10
