### ISSUE TITLE
[Feature Suggestion] Custom Chat Completion like @playerName Format

### ISSUE THREAD

**Issue by g2213swo** [rexlManu/FairyChat#21]
**Scope**: Leverage Paper's custom Tab completion feature to enhance the chat experience in the context of `@playerName` format.

**Why**: The new API from Paper could potentially make the usage of `@playerName` format more user-friendly and intuitive. 

**Reference**:
- **Javadoc**: [Link to Javadoc](https://jd.papermc.io/paper/1.20/org/bukkit/entity/Player.html#addCustomChatCompletions(java.util.Collection))
- **Paper PR**: [Link to PR](https://github.com/PaperMC/Paper/pull/8212)

**Example** Implementation:
Utilizing this could look something like:
```java
// An example of how to add/remove a player's name to/from the tab completion list
                    
// An example of how to get a player by name
Player player = Bukkit.getPlayer("g2213swo");
// It will add the player's name to the tab completion list
player.addCustomChatCompletions(Collections.singletonList("@" + player.getName()));
// It will remove the player's name from the tab completion list
player.removeCustomChatCompletions(Collections.singletonList("@" + player.getName()));

// It will set the player's tab completion list to only contain the player's name
player.setCustomChatCompletions(Collections.singletonList("@" + player.getName()));
```
Thank you for your dedication to this plugin. Its simplicity and efficiency have been a boon to the community. Your efforts are greatly appreciated.

**Comment by rexlManu** [comment]
Hi,

I didn't know that this exists. I'm following always the paper release news but have missed it.

I will add it to my todo and implement it in near future.

Thanks for your suggestion and your kindly words about my work!

**Comment by g2213swo** [comment]
> I don't think that it's a good idea to let players use placeholders from MP or PAPI in their messages

Indeed, you're right. MP and PAPI are designed for server administrators. Allowing players to use them might cause them unease or confusion.

**Comment by rexlManu** [comment]
Hi, I checked it out and it's pretty funky and not really stable. It also bugs with commands, so highlights don't work with them. So for now I will not add this until I found a b etter solution for it.
