### ISSUE TITLE
[BUG] Cannot use placeholders with chat colors

### ISSUE THREAD

**Issue by LuluxClient** [rexlManu/FairyChat#22]
If I want to use a placeholder that outputs a color for example %luckperms_suffix% in the chat format it won't output anything even tho the /papi parse me outputs the correct thing (minimessage)

**Comment by rexlManu** [comment]
Hi, please read more about the placeholder [here](https://github.com/rexlManu/FairyChat/blob/master/.github/docs/PLACEHOLDERS.md). We also provide first party support for LuckPerms.

In your case, the following should work for you:
```
<fc_luckperms_username_color><sender_name><fc_luckperms_username_color>
```
You need to set the `username` metadata with a html color code!
