### ISSUE TITLE
PLACEHOLDERS! PLS! IT'S A BUG

### ISSUE THREAD

**Issue by ChibeMeliodas** [rexlManu/FairyChat#23]
when I try to put %% it automatically puts more percentages, and when I remove it, it also removes it, so I can't make the placeholder work

![Screenshot_21](https://github.com/rexlManu/FairyChat/assets/33189940/688442c6-366a-43d5-8679-a934e6f6efd7)
![Screenshot_22](https://github.com/rexlManu/FairyChat/assets/33189940/bfc34c5b-4801-489c-869f-8f0fdf705d25)
![Screenshot_24](https://github.com/rexlManu/FairyChat/assets/33189940/bb47a143-6a57-46bc-8661-9f9cfd2d7b56)
![Screenshot_25](https://github.com/rexlManu/FairyChat/assets/33189940/e81ed219-8ae3-4be2-8abb-2c5aed8c09c0)

**Comment by rexlManu** [comment]
Hi, does deluxetags require the double % percentage? Normally `<papi:'deluxetags_tag'>` should work as intended and show the result. Otherwise try `<papi:'%deluxetags_tag%'>`
