### ISSUE TITLE
[Suggestion] Allow admins to delete messages

### ISSUE THREAD

**Issue by FaultyFunctions** [rexlManu/FairyChat#59]
Hello! I think it would be really nice to implement a way for admins to remove chat messages and have that message be deleted for everyone like how Chat Control Red does it. Theirs shows a little X before each chat message that and admin can click and have anyone's message be removed. I believe this would involve packet manipulation? I'm not entirely sure to be honest, but it would be a lovely feature to have!

**Comment by rexlManu** [comment]
I'm assuming ChatControlRed just resents all messages except the deleted message, if a message gets deleted? You can't remove a already sent message without that trick. Also that most not all clients / servers have reporting disabled, the message deletion feature will not work really reliable

**Comment by FaultyFunctions** [comment]
Yeah doing more research it seems like they store the old messages, then when you want to delete one it floods the chat with the last 100 messages minus the one you wanted to delete. Hmm it's unfortunate that this hacky solution is the only way to implement this feature. Feel free to close this issue if you don't wanna implement this. Thanks for the reply!
